### ISSUE TITLE
Reverse.html to be the one as index.html?

### ISSUE THREAD

**Issue by chungonion** [police-github/police-github.github.io#2]
I noticed that there is a feature for reverse search (i.e. search name instead of id), but may I know why it is not used as index.html in police-github.github.io site? (I personally think it will be more handy if user can see it, so that they will use it, say for boycotting the police)...

**Comment by police-github** [comment]
cause i tailor-made it for someone who requested it.
btw, just changed it to index.html.

**Comment by chungonion** [comment]
Thanks and I really appreciate your effort!
